version: 2
jobs:
  build:
    docker:
      - image: tokenio/circleci

    steps:
      - checkout

      - deploy:
            command: |
                echo "dev $CIRCLE_PROJECT_REPONAME $CIRCLE_SHA1 $CIRCLE_BUILD_NUM" | ssh circleci@vpn.token.io -T

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
